services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - GENERATION_PROVIDER=demo
      - AUTH_PROVIDER=simple
      - RETRIEVAL_PROVIDER=template
      - ENABLED_DATA_SOURCES=memory
      - AUTH_SECRET_KEY=demo_secret_key_for_development
    restart: unless-stopped
    command: ["uv", "run", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
