[project]
name = "backend"
version = "0.1.0"
description = "AI Ground Truth Generator Backend"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "openai>=1.82.1",
    "pydantic>=2.11.5",
    "python-dotenv>=1.1.0",
    "uvicorn>=0.34.2",
]
